kLeft = keyboard_check(ord("A"))
kRight = keyboard_check(ord("D"))
kUp = keyboard_check(ord("W"))
kDown = keyboard_check(ord("S"))
rotateR = keyboard_check_pressed(vk_right)
rotateL = keyboard_check_pressed(vk_left)